service: Turiri
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
 

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  getAll:
    handler: src/handlers/getAll.handler
    events:
      - httpApi:
          path: /users
          method: GET
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: GET
          
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

